export const BUSINESS_CATEGORIES = [
    { key: 'cozy', value: 'Cozy', color: '#2915a0' },
    { key: 'funky', value: 'Funky', color: '#2f3edc' },
    { key: 'therapy', value: 'Therapy', color: '#914b50' },
    { key: 'soothing', value: 'Soothing', color: '#1f2418' },
    { key: 'calming', value: 'Calming', color: '#a698c0' },
    { key: 'private', value: 'Private', color: '#43e220' },
    { key: 'asmr', value: 'ASMR', color: '#603f50' },
    { key: 'teamMeeting', value: 'Team meeting', color: '#deb550' },
    { key: 'legal', value: 'Legal', color: '#6912a0' },
    { key: 'mediation', value: 'Mediation', color: '#dc7e10' },
    { key: 'focused', value: 'Focused', color: '#7a785b' },
    { key: 'energizing', value: 'Energizing', color: '#b4c9e0' },
    { key: 'counselling', value: 'Counselling', color: '#ea392f' },
    { key: 'nature', value: 'Nature', color: '#9ecd50' },
    { key: 'restorative', value: 'Restorative', color: '#da2690' },
    { key: 'secluded', value: 'Secluded', color: '#5734fd' },
    { key: 'consulting', value: 'Consulting', color: '#517f60' },
    { key: 'therapeutic', value: 'Therapeutic', color: '#5ba555' },
    { key: 'meditation', value: 'Mediation', color: '#382ba8' },
    { key: 'sounds', value: 'Sounds', color: '#1ee510' },
    { key: 'retreat', value: 'Retreat', color: '#3219ad' },
];
