import { ConfigKeysType } from './config.interface';

export const ConfigKeys: readonly ConfigKeysType[] = [
    'rabbitMqCoreQueue',
    'rabbitMqAuthQueue',
    'rabbitMqNotificationsQueue',
    'rabbitMqPaymentQueue',
    'rabbitMqUser',
    'rabbitMqPass',
    'rabbitMqHost',
    'mongoUri',
    'jwtSecret',
    'frontendUrl',
    'gatewayPort',
    'smtpUser',
    'smtpPass',
    'smtpUserName',
    'defaultServerIp',
    'appId',
    'appCertificate',
    'uploadBucket',
    'storageHostname',
    'accessKey',
    'secretAccessKey',
    'stripeApiKey',
    'stripeWebhookSecret',
    'stripeExpressWebhookSecret',
    'mandrillApiKey',
    'isLocal',
    'nodeEnv',
    'port',
    'emailService',
];

export const DefaultConfigValues: Record<ConfigKeysType, string | number | boolean> = {
    rabbitMqCoreQueue: 'rabbitMqCoreQueue',
    rabbitMqAuthQueue: 'rabbitMqAuthQueue',
    rabbitMqNotificationsQueue: 'rabbitMqNotificationsQueue',
    rabbitMqPaymentQueue: 'rabbitMqPaymentQueue',
    rabbitMqUser: 'rabbituser',
    rabbitMqPass: 'rabbitpass',
    rabbitMqHost: 'rabbitmq',
    mongoUri: 'mongodb://mongo:27017/theliveoffice',
    jwtSecret: 'jwtSecret',
    frontendUrl: 'http://localhost:8000',
    gatewayPort: '3000',
    smtpUser: 'vladislav.e@fora-soft.com',
    smtpPass: 'xoiwmfwquupyhcoj',
    smtpUserName: 'The LiveOffice',
    defaultServerIp: 'localhost',
    appId: '9d88cb47f5e648c1b2b3c6ee8563e655',
    appCertificate: '5eeb44cc55e94718ab3cdde84f278174',
    uploadBucket: 'liveoffice',
    storageHostname: 'ewr1.vultrobjects.com',
    accessKey: 'XSGnjAdSXoRYhTAntNNJYhHCY7MeJseUujCDvcHK',
    secretAccessKey: '04F4BOA4E0QRBSF0BW37',
    stripeApiKey: '',
    stripeWebhookSecret: '',
    stripeExpressWebhookSecret: '',
    mandrillApiKey: '',
    isLocal: false,
    nodeEnv: 'develop',
    port: 4000,
    emailService: 'gmail',
}
