export const CONFIG_PROVIDER = 'CONFIG_PROVIDER';
export const CORE_PROVIDER = 'CORE_PROVIDER';
export const AUTH_PROVIDER = 'AUTH_PROVIDER';
export const NOTIFICATIONS_PROVIDER = 'NOTIFICATIONS_PROVIDER';
export const PAYMENTS_PROVIDER = 'PAYMENTS_PROVIDER';
export const MEDIA_SERVER_PROVIDER = 'MEDIA_SERVER_PROVIDER';
export const SCALING_PROVIDER = 'SCALING_PROVIDER';
export const SOCKET_PROVIDER = 'SOCKET_PROVIDER';
