export enum CoreBrokerPatterns {
  GetBusinessCategories = 'get_business_categories',
  GetCountryStatistics = 'get_country_statistics',
  GetMediaCategories = 'get_media_categories',
  GetMedias = 'get_medias',
  GetUserTemplateMedias = 'get_user_template_medias',
  CreateMediaCategory = 'create_media_category',
  CreateMedia = 'create_media',
  CreateUserTemplateMedia = 'create_user_template_media',
  UploadMediaCategoryFile = 'upload_media_category_file',
  UpdateBusinessCategory = 'update_business_category',
  UploadMediaFile = 'upload_media_file',
  UpdateMediaCategory = 'update_media_category',
  UploadUserTemplateMediaFile = 'upload_user_template_media_file',
  UpdateMedia = 'udpate_media',
  DeleteBusinessCategories = 'delete_business_categories',
}
