export enum CoreBrokerPatterns {
  GetBusinessCategories = 'get_business_categories',
  GetCountryStatistics = 'get_country_statistics',
  GetMediaCategories = 'get_media_categories',
  GetAdminMediaCategories = 'get_admin_media_categories',
  GetMedias = 'get_medias',
  CreateMediaCategory = 'create_media_category',
  CreateMedia = 'create_media',
  UploadMediaCategoryFile = 'upload_media_category_file',
  UpdateBusinessCategory = 'update_business_category',
  UploadMediaFile = 'upload_media_file',
  UpdateMediaCategory = 'update_media_category',
  UpdateMedia = 'udpate_media',
  DeleteMedias = 'delete_medias',
  DeleteMediaCategories = 'delete_media_categories',
  DeleteBusinessCategories = 'delete_business_categories',
}
