export enum PaymentsBrokerPatterns {
  CreateStripeExpressAccount = 'create_stripe_express_account',
  CreateStripeAccountLink = 'create_stripe_account_link',
  LoginStripeExpressAccount = 'login_stripe_express_account',
  DeleteStripeExpressAccount = 'delete_stripe_express_account',
  CreatePaymentIntent = 'create_payment_intent',
  CancelPaymentIntent = 'cancel_payment_intent',
  HandleWebHook = 'handle_webhook',
  HandleExpressWebHook = 'handle_express_webhook',
  GetStripeSubscriptionProducts = 'get_stripe_subscriptions_products',
  GetStripeTemplateProducts = 'get_stripe_templates_products',
  GetStripeCheckoutSession = 'get_stripe_checkout_session',
  GetStripePortalSession = 'get_stripe_portal_session',
  GetStripeSubscription = 'get_stripe_subscription',
  GetStripeTemplateProduct = 'get_template_stripe_product',
  GetStripeTemplateProductByName = 'get_template_stripe_product_by_name',
  CreateStripeTemplateProduct = 'create_template_stripe_product',
  GetStripeProductCheckoutSession = 'get_stripe_product_checkout_session',
  GetStripeCharges = 'get_stripe_charges',
}
