export enum UserTemplatesBrokerPatterns {
  GetUserTemplate = 'get_user_template',
  CreateUserTemplate = 'create_user_template',
  GetUserTemplateByTemplateId = 'get_user_template_by_template_id',
  GetUserTemplateById = 'get_user_template_by_id',
  GetUserTemplates = 'get_user_templates',
  UpdateUserTemplate = 'update_user_template',
  GetUsersTemplates = 'get_users_templates',
  DeleteUsersTemplates = 'delete_users_templates',
  UploadUserTemplateFile = 'upload_user_template_file',
  UploadProfileTemplateFile = 'upload_profile_template_file',
  CountUserTemplates = 'count_user_templates',
  UpdateUserTemplateUsageNumber = 'update_user_template_usage_number',
  DeleteLeastUsedTemplates = 'delete_least_user_templates',
}
