FROM node:18.9.1-alpine

ARG VULTR_STORAGE_HOSTNAME
ENV VULTR_STORAGE_HOSTNAME=$VULTR_STORAGE_HOSTNAME

RUN apk add --no-cache curl && curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | PNPM_VERSION=8.15.5 node

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache g++ make

WORKDIR /app

RUN mkdir -p services/frontend-service

COPY ./pnpm-workspace.yaml ./
COPY ./.npmrc ./
COPY ./shared ./shared

RUN pnpm add nx -D -w

COPY ./services/frontend-service/package.json ./services/frontend-service

COPY ./services/frontend-service ./services/frontend-service

RUN pnpm install

RUN npx nx run-many --target=build --projects=shared-types,shared-const,shared-utils

EXPOSE 8000

CMD /wait && pnpm --filter frontend-service dev
