FROM node:18.7.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app

COPY ./package*.json ./

RUN npm ci --legacy-peer-deps --force

ARG VULTR_STORAGE_HOSTNAME
ENV VULTR_STORAGE_HOSTNAME=$VULTR_STORAGE_HOSTNAME

COPY ./ ./

RUN npm run build

EXPOSE 8000

CMD /wait && npm run dev
