stages:
  - sonarqube_scan
  - update_traefik
  - build_scaling_instance_image
  - update_test
  - update_dev_staging
  - update_staging_services
  - update_staging_config
  - update
  - update_jira_issues
  - update_demo_traefik
  - update_demo
  - update_production_traefik
  - update_production
  - auto_push

variables:
  GIT_DEPTH: 10

.docker-base:
  image: forasoft/dind
  environment:
    name: ${CI_COMMIT_REF_NAME}
  interruptible: true

include:
  - 'pipelines/demo.yml'
  - 'pipelines/develop.yml'
  - 'pipelines/testing.yml'
  - 'pipelines/autopush_code.yml'
  - 'pipelines/production.yml'
  - 'pipelines/build_instance.yml'
  - 'pipelines/sonarqbue.yml'
  - 'pipelines/jira.yml'

