import { Profile } from '../../types';

export const initialProfileState = {
    id: '',
    fullName: '',
    position: '',
    profileAvatar: {
        id: '',
        url: '',
        size: 0,
        mimeType: '',
    },
    companyName: '',
    email: '',
    contactEmail: '',
    description: '',
    languages: [],
    socials: [],
    businessCategories: [],
    signBoard: 'default',
    subscriptionPlanKey: 'House',
    nextSubscriptionPlanKey: 'House',
    prevSubscriptionPlanKey: 'House',
    stripeAccountId: '',
    stripeEmail: '',
    stripeSubscriptionId: '',
    renewSubscriptionTimestampInSeconds: 0,
    isStripeEnabled: false,
    isSubscriptionActive: false,
    maxTemplatesNumber: 0,
    maxMeetingTime: 0,
    wasSuccessNotificationShown: false,
    country: '',
    isProfessionalTrialAvailable: false,
    shouldShowTrialExpiredNotification: false,
} as Profile;
