FROM node:18.7.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./payment-service

COPY ./payment-service/package*.json ./payment-service/

RUN npm ci --silent --legacy-peer-deps --force --prefix=/app/payment-service

COPY ./payment-service ./payment-service/

RUN npm run build --prefix=/app/payment-service

EXPOSE 5000

CMD /wait && npm run start:dev --prefix=/app/payment-service

