FROM node:18.7.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache g++ make

WORKDIR /app

COPY ./shared ./shared

RUN mkdir ./notifications-service

COPY ./notifications-service/package*.json ./notifications-service/

RUN npm ci --silent --legacy-peer-deps --prefix=/app/notifications-service

COPY ./notifications-service ./notifications-service/

RUN npm run build --prefix=/app/notifications-service

CMD /wait && npm run dev --prefix=/app/notifications-service
