log:
  level: DEBUG

api:
  dashboard: false
  insecure: false

providers:
  docker:
    network: traefikpublic
    exposedByDefault: false


certificatesResolvers:
  simple-resolver:
    acme:
      httpchallenge:
        entrypoint: http
      email: nam@namnm.com
      storage: /letsencrypt/acme.json
      tlschallenge: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

http:
  routers:
    router0:
      service: "chatruume"
      rule: "Host(`chatruume.com`)"
#      tls:
#        cert-resolver: "simple-resolver"

  services:
    chatruume:
      loadBalancer:
        servers:
          - url: http://5.181.161.73:80/
        passHostHeader: true

accessLog: {}
