log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: traefikpublic
    exposedByDefault: false
  file:
    filename: /traefik/dynamic_conf.yml

certificatesResolvers:
  simple-resolver:
    acme:
      httpchallenge:
        entrypoint: http
      email: nam@namnm.com
      storage: /letsencrypt/acme.json
      tlschallenge: true
  wildcard-resolver:
    acme:
      dnschallenge:
        provider: route53
      email: nam@namnm.com
      storage: /letsencrypt/wildcard-resolver.json

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

accessLog:
  format: json
