FROM node:16.16.0-alpine

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache g++ make

RUN mkdir /app
WORKDIR /app

COPY ./shared ./shared

RUN mkdir ./config-service

COPY ./config-service/package*.json ./config-service/

RUN cd ./config-service && npm i --legacy-peer-deps

COPY ./config-service ./config-service/

EXPOSE 4000

CMD ["npm", "run", "--prefix", "/app/config-service", "dev"]
