FROM node:16.9.0-alpine

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./core-service

COPY ./core-service/package*.json ./core-service/

RUN cd ./core-service && npm ci --silent --legacy-peer-deps

COPY ./core-service ./core-service/

CMD ["npm", "run", "--prefix", "/app/core-service", "start:dev"]
