export const CONFIG_PROVIDER = 'CONFIG_PROVIDER';
export const CORE_PROVIDER = 'CORE_PROVIDER';
export const AUTH_PROVIDER = 'AUTH_PROVIDER';
export const NOTIFICATIONS_PROVIDER = 'NOTIFICATIONS_PROVIDER';
export const INSTANCE_MANAGER_PROVIDER = 'INSTANCE_MANAGER_PROVIDER';