export enum TemplateBrokerPatterns {
  GetCommonTemplates = "get_common_templates",
  GetUserTemplate = "get_user_template",
  CreateUserTemplate = "create_user_template",
  GetUserTemplateByTemplateId = "get_user_template_by_template_id",
  GetUserTemplateById = "get_user_template_by_id",
  GetUserTemplates = "get_user_templates",
  GetCommonTemplate = "get_common_template",
  GetCommonTemplateById = "get_common_template_by_id",
  UpdateUserTemplate = "update_user_template",
  GetUsersTemplates = "get_users_templates",
  DeleteUsersTemplates = "delete_users_templates",
  AddTemplateToUser = "add_template_to_user",
  CreateTemplate = "create_template",
  UploadTemplateFile = "upload_template_file",
  UploadProfileTemplateFile = "upload_profile_template_file",
  UpdateTemplate = "update_template",
}
