export const emailTemplates = {
  emailVerification: 'email-verification',
  welcomeEmail: 'welcome-email',
  deletedAccount: 'deleted-account',
  stripeLinked: 'stripe-linked',
  resetPassword: 'reset-password',
  meetingInvite: 'meeting-invitation',
  meetingInviteIcs: 'meeting-invitation-with-ics-file',
  scheduledMeeting: 'scheduled-meeting',
  emailUpdated: 'email-changed',
  emailOldUpdated: 'email-old-changed',
  codeVerification: 'code-sent',
  subscriptionSuccessful: 'subscription-successful',
  subscriptionBusiness: 'subscription-business',
  contactUs: 'contact-us',
  trialExpires: 'trial-expires',
  blockedAccount: 'account-was-blocked',
  deletedAccountByAdmin: 'account-was-deleted',
  unblockedAccount: 'unblocked-account',
};
