export const emailTemplates = {
  emailVerification: 'email-verification',
  welcomeEmail: 'welcome-email',
  deletedAccount: 'deleted-account',
  stripeLinked: 'stripe-linked',
  resetPassword: 'reset-password',
  meetingInvite: 'meeting-invitation',
  meetingInviteIcs: 'meeting-invitation-with-ics-file',
  emailUpdated: 'email-changed',
  emailOldUpdated: 'email-old-changed',
  codeVerification: 'code-sent',
  subscriptionSuccessful: 'subscription-successful',
  contactUs: 'contact-us',
  trialExpires: 'trial-expires',
};
