export const LANGUAGES_TAGS = [
    { key: 'en', value: 'English' },
    { key: 'gr', value: 'German' },
    { key: 'mand', value: 'Mandarin Chinese' },
    { key: 'sp', value: 'Spanish' },
    { key: 'hind', value: 'Hindi' },
    { key: 'beng', value: 'Bengali' },
    { key: 'port', value: 'Portuguese' },
    { key: 'rus', value: 'Russian' },
    { key: 'jap', value: 'Japanese' },
    { key: 'mar', value: 'Marathi' },
    { key: 'tel', value: 'Telugu' },
    { key: 'turk', value: 'Turkish' },
    { key: 'ker', value: 'Korean' },
    { key: 'fr', value: 'French' },
    { key: 'viet', value: 'Vietnamese' },
    { key: 'tam', value: 'Tamil' },
    { key: 'jav', value: 'Javanese' },
    { key: 'ita', value: 'Italian' },
    { key: 'guj', value: 'Gujarati' },
    { key: 'bhoj', value: 'Bhojpuri' },
    { key: 'hak', value: 'Hakka' },
    { key: 'hau', value: 'Hausa' },
    { key: 'kan', value: 'Kannada' },
    { key: 'ind', value: 'Indonesian' },
    { key: 'pol', value: 'Polish' },
    { key: 'yor', value: 'Yoruba' },
    { key: 'odia', value: 'Odia' },
    { key: 'maith', value: 'Maithili' },
    { key: 'bur', value: 'Burmese' },
    { key: 'sund', value: 'Sunda' },
    { key: 'ukr', value: 'Ukrainian' },
    { key: 'igbo', value: 'Igbo' },
    { key: 'sind', value: 'Sindhi' },
    { key: 'rom', value: 'Romanian' },
    { key: 'tag', value: 'Tagalog' },
    { key: 'dut', value: 'Dutch' },
    { key: 'amh', value: 'Amharic' },
    { key: 'mag', value: 'Magahi' },
    { key: 'thai', value: 'Thai' },
    { key: 'sar', value: 'Saraiki' },
    { key: 'khmer', value: 'Khmer' },
    { key: 'som', value: 'Somali' },
    { key: 'ceb', value: 'Cebuano' },
    { key: 'nep', value: 'Nepali' },
    { key: 'assa', value: 'Assamese' },
    { key: 'sinh', value: 'Sinhalese' },
    { key: 'bav', value: 'Bavarian' },
    { key: 'gre', value: 'Greek' },
    { key: 'chit', value: 'Chittagonian' },
    { key: 'kaz', value: 'Kazakh' },
    { key: 'dec', value: 'Deccan' },
    { key: 'hung', value: 'Hungarian' },
    { key: 'kinya', value: 'Kinyarwanda' },
    { key: 'zulu', value: 'Zulu' },
    { key: 'rundi', value: 'Rundi' },
    { key: 'cze', value: 'Czech' },
    { key: 'uygh', value: 'Uyghur' },
    { key: 'syl', value: 'Sylheti' },
    { key: 'urd', value: 'Urdu' },
    { key: 'w-punj', value: 'Western Punjabi\t' },
    { key: 'w-chin', value: 'Wu Chinese' },
    { key: 'y-chin', value: 'Yue Chinese' },
    { key: 'egp-tar', value: 'Egyptian Arabic' },
    { key: 'iran-pers', value: 'Iranian Persian' },
    { key: 's-min', value: 'Southern Min' },
    { key: 'j-chin', value: 'Jin Chinese' },
    { key: 'x-chin', value: 'Xiang Chinese' },
    { key: 'ea-pun', value: 'Eastern Punjabi' },
    { key: 'sud-ar', value: 'Sudanese Arabic' },
    { key: 'alg-ar', value: 'Algerian Arabic' },
    { key: 'moro-ar', value: 'Moroccan Arabic' },
    { key: 'n-uzb', value: 'Northern Uzbek' },
    { key: 'n-leva-ar', value: 'North Levantine Arabic' },
    { key: 'sa-ara', value: 'Saʽidi Arabic' },
    { key: 'g-chi ', value: 'Gan Chinese' },
    { key: 'n-pash', value: 'Northern Pashto' },
    { key: 'chh', value: 'Chhattisgarhi' },
    { key: 'mal', value: 'Malaysian' },
    { key: 'mes-ara', value: 'Mesopotamian Arabic' },
    { key: 'n-kurd', value: 'Northern Kurdish' },
    { key: 'he-ara', value: 'Hejazi Arabic' },
    { key: 'nig-ful', value: 'Nigerian Fulfulde' },
    { key: 's-azer', value: 'South Azerbaijani' },
    { key: 's-lev-ara', value: 'South Levantine Arabic' },
    { key: 'tun-ara', value: 'Tunisian Arabic' },
    { key: 'san-sp-ara', value: 'Sanaani Spoken Arabic' },
    { key: 'n-min', value: 'Northern Min' },
    { key: 's-pash', value: 'Southern Pashto' },
    { key: 'ta-ara', value: 'Taʽizzi-Adeni Arabic' },
    { key: 'ea-min', value: 'Eastern Min' },
];
