FROM node:18.7.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git

WORKDIR /app

COPY ./shared ./shared

RUN mkdir ./media-server-service

COPY ./media-server-service/package*.json ./media-server-service/

RUN npm ci --legacy-peer-deps --silent --prefix=/app/media-server-service

COPY ./media-server-service ./media-server-service/

CMD /wait && npm run dev --prefix=/app/media-server-service
