FROM node:18.9.1-alpine

RUN apk add --no-cache curl && curl -sL https://unpkg.com/@pnpm/self-installer | node

WORKDIR /app

RUN mkdir -p services/config-service

COPY ./pnpm-workspace.yaml ./
COPY ./.npmrc ./
COPY ./shared ./shared

RUN pnpm add nx -D -w

COPY ./services/config-service/package.json ./services/config-service

RUN pnpm install

COPY ./services/config-service ./services/config-service

RUN npx nx run-many --target=build --projects=shared-utils,shared-const,shared-types,config-service

EXPOSE 4000

CMD ["pnpm", "--filter", "config-service", "dev"]
