version: "3.7"

networks:
  liveoffice_instance:

services:
  web:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"

  livekit-service:
    build:
      context: ../../services/
      dockerfile: ./livekit-service/Dockerfile
      args:
        - LIVEKIT_IP
        - LIVEKIT_API_KEY
        - LIVEKIT_API_SECRET
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "6789:6789"

  meeting-socket-service:
    build:
      context: ../../services
      dockerfile: ./meeting-socket-service/Dockerfile
    restart: unless-stopped
    ports:
      - '8180:8180'
    environment:
      WAIT_HOSTS: config-service:4000
      WAIT_TIMEOUT: 60000

  config-service:
    build:
      context: ../../services
      dockerfile: ./config-service/Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - RABBIT_MQ_MEDIA_SERVER_QUEUE=rabbitMqMediaServerQueue
      - RABBIT_MQ_CORE_QUEUE=rabbitMqCoreQueue
      - RABBIT_MQ_USER=rabbituser
      - RABBIT_MQ_PASS=rabbitpass
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_CORE_HOST=${DEFAULT_SERVER_IP}
      - RABBIT_MQ_CORE_PORT
      - ENVIRONMENT
      - LIVEKIT_API_KEY
      - LIVEKIT_API_SECRET
      - LIVEKIT_HOST
      - DEFAULT_SERVER_IP
    depends_on:
      - mongo
      - rabbit