FROM node:16.16.0-alpine

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./socket-service/

COPY ./socket-service/package*.json ./socket-service/

RUN cd ./socket-service && npm ci --silent --legacy-peer-deps

COPY ./socket-service ./socket-service/

EXPOSE 8080

CMD ["npm", "run", "--prefix", "/app/socket-service", "start:dev"]
