import { ICommonTemplate } from "../interfaces/common-template.interface";

interface BaseTemplate
  extends Omit<
    ICommonTemplate,
    "businessCategories" | "previewUrls" | "stripeProductId" | "url"
  > {
  businessCategories: string[];
  imagesUrl?: string;
  videoPath?: string;
  imagePath?: string;
}

export const templatesData: BaseTemplate[] = [
  {
    templateId: 1,
    templateType: 'video',
    videoPath: "/ibiza2",
    imagePath: "/free-ibiza2",
    name: "Ibiza Patio",
    maxParticipants: 2,
    description:
      "Enjoy the visuals and sounds of a crackling firepit and waves crashing nearby. Take a seat in a patio by the beach on the magical island of Ibiza.",
    shortDescription: "Gather round a crackling firepit by the beach",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Sounds",
      "Mediation",
      "Consulting",
      "Therapeutic",
      "Private",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.46,
        left: 0.27,
      },
      {
        bottom: 0.46,
        left: 0.58,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 2,
    templateType: 'video',
    videoPath: "/ibiza3",
    imagePath: "/free-ibiza3",
    name: "Mt Fuji Patio",
    maxParticipants: 3,
    description: "Sit around the firepit with Mount Fuji in the background",
    shortDescription:
      "Sit around the firepit with Mount Fuji in the background",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Sounds",
      "Mediation",
      "Consulting",
      "Therapeutic",
      "Private",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.46,
        left: 0.44,
      },
      {
        bottom: 0.41,
        left: 0.69,
      },
      {
        bottom: 0.41,
        left: 0.19,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 3,
    templateType: 'video',
    videoPath: "/ibiza4",
    imagePath: "/free-ibiza4",
    name: "Ibiza Patio",
    maxParticipants: 4,
    description:
      "Enjoy the visuals and sounds of a crackling firepit and waves crashing nearby. Take a seat in a patio by the beach on the magical island of Ibiza.",
    shortDescription: "Gather round a crackling firepit by the beach",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Sounds",
      "Mediation",
      "Consulting",
      "Therapeutic",
      "Private",
      "ASMR",
      "Team meeting",
    ],
    usersPosition: [
      {
        bottom: 0.47,
        left: 0.37,
      },
      {
        bottom: 0.47,
        left: 0.60,
      },
      {
        bottom: 0.41,
        left: 0.74,
      },
      {
        bottom: 0.41,
        left: 0.17,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 4,
    templateType: 'video',
    videoPath: "/lake_harmony",
    imagePath: "/free-lake_harmony",
    name: "Lakeside Office",
    maxParticipants: 4,
    description:
      "Relax in a super comfy and casual office by the edge of lake Taho. Recharge your batteries with a luminous space.",
    shortDescription: "Get inspired in a calming yet energizing environment",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Consulting",
      "Mediation",
      "Team Meeting",
      "Retreat",
      "Restorative",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.41,
        left: 0.16,
      },
      {
        bottom: 0.46,
        left: 0.39,
      },
      {
        bottom: 0.46,
        left: 0.59,
      },
      {
        bottom: 0.41,
        left: 0.84,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 5,
    templateType: 'video',
    videoPath: "/rustic",
    imagePath: "/free-rustic",
    name: "Countryside Office",
    maxParticipants: 3,
    description:
      "If you need a mental break while working this office will bring a smile to your face ",
    shortDescription: "Enter a rustic office surrounded by Nature",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Consulting",
      "Mediation",
      "Sounds",
      "Calming",
      "Restorative",
      "Nature",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.47,
        left: 0.19,
      },
      {
        bottom: 0.50,
        left: 0.49,
      },
      {
        bottom: 0.50,
        left: 0.76,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 6,
    templateType: 'video',
    videoPath: "/retro",
    imagePath: "/free-retro",
    name: "1970's Office",
    maxParticipants: 3,
    description:
      "Enjoy a warm 1970's style office and let your eyes can explore this rich environment",
    shortDescription: "Enjoy the rich visuals of a funky era",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Consulting",
      "Sounds",
      "Private",
      "Funky",
      "Cozy",
    ],
    usersPosition: [
      {
        bottom: 0.5,
        left: 0.49,
      },
      {
        bottom: 0.5,
        left: 0.83,
      },
      {
        bottom: 0.5,
        left: 0.15,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 7,
    templateType: 'video',
    videoPath: "/tat",
    imagePath: "/free-tat",
    name: "Modern office",
    maxParticipants: 2,
    description:
      "This is your one-on-one place where private and intimate conversations can take place while soaking in the sunlight",
    shortDescription: "Share a private conversation in a sunny office",
    type: "free",
    isAudioAvailable: false,
    businessCategories: [
      "Counselling",
      "Consulting",
      "Calming",
      "Energizing",
      "Private",
    ],
    usersPosition: [
      {
        bottom: 0.44,
        left: 0.8,
      },
      {
        bottom: 0.44,
        left: 0.15,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 8,
    templateType: 'video',
    videoPath: "/cascadia",
    imagePath: "/cascadia",
    name: "Cascadia",
    maxParticipants: 6,
    description:
      "Enter the patio of Cascadia, an imaginary castle on the edge of waterfalls",
    shortDescription:
      "Meet and chat in an idyllic patio with a dramatic backdrop",
    type: "paid",
    priceInCents: 1000,
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Consulting",
      "Team Meeting",
      "Secluded",
      "Energizing",
      "Restorative",
      "Nature",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.25,
        left: 0.62,
      },
      {
        bottom: 0.25,
        left: 0.44,
      },
      {
        bottom: 0.23,
        left: 0.78,
      },
      {
        bottom: 0.25,
        left: 0.3,
      },
      {
        bottom: 0.22,
        left: 0.91,
      },
      {
        bottom: 0.21,
        left: 0.17,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 9,
    templateType: 'video',
    videoPath: "/cascadia",
    imagePath: "/free-cascadia",
    name: "Cascadia",
    maxParticipants: 4,
    description:
      "Enter the patio of Cascadia, an imaginary castle on the edge of waterfalls",
    shortDescription:
      "Meet and chat in an idyllic patio with a dramatic backdrop",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Consulting",
      "Team Meeting",
      "Secluded",
      "Energizing",
      "Restorative",
      "Nature",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.25,
        left: 0.62,
      },
      {
        bottom: 0.25,
        left: 0.44,
      },
      {
        bottom: 0.23,
        left: 0.78,
      },
      {
        bottom: 0.25,
        left: 0.3,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 10,
    templateType: 'video',
    videoPath: "/therapist-hi",
    imagePath: "/free-therapist-hi",
    name: "Therapy Office (at the desk)",
    maxParticipants: 2,
    description: "Meet your client at the desk of your office",
    shortDescription:
      "This office is modern yet iconic featuring a calming vista",
    type: "free",
    isAudioAvailable: true,
    businessCategories: ["Counselling", "Calming", "Private", "ASMR"],
    usersPosition: [
      {
        bottom: 0.49,
        left: 0.56,
      },
      {
        bottom: 0.38,
        left: 0.36,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 11,
    templateType: 'video',
    videoPath: "/therapist-session",
    imagePath: "/free-therapist-session",
    name: "Therapy Office (on the couch)",
    maxParticipants: 2,
    description:
      "Sit in a luxurious armchair as your client relaxes on a couch",
    shortDescription:
      "This office is modern yet iconic featuring a calming vista",
    type: "free",
    isAudioAvailable: true,
    businessCategories: ["Counselling", "Calming", "Private", "ASMR"],
    usersPosition: [
      {
        bottom: 0.45,
        left: 0.36,
      },
      {
        bottom: 0.3,
        left: 0.75,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 12,
    templateType: 'video',
    videoPath: "/executive",
    imagePath: "/free-executive",
    name: "New York Executive",
    maxParticipants: 3,
    description:
      "This office offers a focused environment and a splendid vista on New York's Central Park",
    shortDescription:
      "Lead meetings in an office with a prime view on Central Park ",
    type: "free",
    isAudioAvailable: false,
    businessCategories: [
      "Legal",
      "Consulting",
      "Focused",
      "Energizing",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.63,
        left: 0.73,
      },
      {
        bottom: 0.35,
        left: 0.45,
      },
      {
        bottom: 0.56,
        left: 0.34,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 13,
    templateType: 'video',
    videoPath: "/executivebeach",
    imagePath: "/free-executivebeach",
    name: "Tropical Executive",
    maxParticipants: 3,
    description: "Enjoy this luxurious office that inspires calm and balance",
    shortDescription: "A classical office featuring ocean views",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Legal",
      "Consulting",
      "Mediation",
      "ASMR",
      "Private",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.51,
        left: 0.55,
      },
      {
        bottom: 0.33,
        left: 0.82,
      },
      {
        bottom: 0.33,
        left: 0.32,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 14,
    templateType: 'video',
    videoPath: "/office",
    imagePath: "/free-office",
    name: "Regency Office",
    maxParticipants: 2,
    description:
      "If you're looking for a calm safe space for a private conversation this may your spot",
    shortDescription: "Treat your guests to a warm and balanced ambiance ",
    type: "free",
    isAudioAvailable: false,
    businessCategories: ["Legal", "Consulting", "Private", "Calming"],
    usersPosition: [
      {
        bottom: 0.48,
        left: 0.8,
      },
      {
        bottom: 0.51,
        left: 0.14,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 15,
    templateType: 'video',
    videoPath: "/graffiti",
    imagePath: "/free-graffiti",
    name: "Apocalypto",
    maxParticipants: 4,
    description:
      "Grab a crate and gather by a stunning graffiti and a burning barrel",
    shortDescription: "The ultimate urban location",
    type: "free",
    isAudioAvailable: true,
    businessCategories: ["Team meeting", "Calming", "Private", "ASMR"],
    usersPosition: [
      {
        bottom: 0.29,
        left: 0.3,
      },
      {
        bottom: 0.30,
        left: 0.52,
      },
      {
        bottom: 0.23,
        left: 0.09,
      },
      {
        bottom: 0.25,
        left: 0.82,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 16,
    templateType: 'video',
    videoPath: "/graffiti",
    imagePath: "/graffiti",
    name: "Apocalypto",
    maxParticipants: 6,
    description:
      "Grab a crate and gather by a stunning graffiti and a burning barrel",
    shortDescription: "The ultimate urban location",
    type: "paid",
    priceInCents: 1000,
    isAudioAvailable: true,
    businessCategories: ["Team meeting", "Calming", "Private", "ASMR"],
    usersPosition: [
      {
        bottom: 0.29,
        left: 0.3,
      },
      {
        bottom: 0.30,
        left: 0.52,
      },
      {
        bottom: 0.23,
        left: 0.09,
      },
      {
        bottom: 0.13,
        left: 0.63,
      },
      {
        bottom: 0.25,
        left: 0.82,
      },
      {
        bottom: 0.5,
        left: 0.47,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 17,
    templateType: 'video',
    videoPath: "/fireandfog",
    imagePath: "/free-fireandfog",
    name: "Modern 1-on-1: Fog",
    maxParticipants: 2,
    shortDescription: "A soothing and calming ambiance",
    description: "A good view to share a good conversation",
    type: "free",
    isAudioAvailable: true,
    businessCategories: ["Therapy", "Calming", "Private", "Soothing", "ASMR"],
    usersPosition: [
      {
        bottom: 0.22,
        left: 0.67,
      },
      {
        bottom: 0.22,
        left: 0.33,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 18,
    templateType: 'video',
    videoPath: "/ocean_vista",
    imagePath: "/free-ocean_vista",
    name: "Modern 1-on-1: Ocean",
    maxParticipants: 2,
    shortDescription: "Take a seat in a restorative and calming set",
    description: "A beautiful view to refresh the mind",
    type: "free",
    isAudioAvailable: true,
    businessCategories: ["Therapy", "Calming", "Private", "Soothing", "ASMR"],
    usersPosition: [
      {
        bottom: 0.31,
        left: 0.65,
      },
      {
        bottom: 0.31,
        left: 0.31,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 19,
    templateType: 'video',
    videoPath: "/centralpark",
    imagePath: "/free-centralpark",
    name: "Modern 1-on-1: Central Park",
    maxParticipants: 2,
    shortDescription:
      "Enjoy a conversation overlooking New York's Central Park",
    description: "A calming view of shadows moving over Central Park",
    type: "free",
    isAudioAvailable: true,
    businessCategories: ["Therapy", "Calming", "Private", "Soothing", "ASMR"],
    usersPosition: [
      {
        bottom: 0.22,
        left: 0.67,
      },
      {
        bottom: 0.22,
        left: 0.33,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 20,
    templateType: 'video',
    videoPath: "/ralph_lauren",
    imagePath: "/free-ralph_lauren",
    name: "Virtual Luxury (Store)",
    maxParticipants: 4,
    description: "Ralph Lauren's signature Shelter Point",
    shortDescription: "Shelter Point is now Live",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Store",
      "Team meeting",
      "Calming",
      "Soothing",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.64,
        left: 0.56,
      },
      {
        bottom: 0.31,
        left: 0.32,
      },
      {
        bottom: 0.29,
        left: 0.84,
      },
      {
        bottom: 0.34,
        left: 0.07,
      },
    ],
    links: [
      {
        item: "https://www.ralphlaurenhome.com/products/Furniture/item.aspx?haid=7&collId=&shaid=&sort=&itemId=38525&phaid=",
        position: { top: 0.8, left: 0.9 },
      },
      {
        item: "https://www.ralphlauren.com/home-shelter-point-lifestyle-cg/umber-walnut-drinks-table/100001390.html?dwvar_100001390_home-furniture-finish=Oiled%20Walnut&cgid=home-shelter-point-lifestyle-cg&webcat=search#ab=en_US_HomeLP_Slot_1_S1_L1_SHOP&start=1&cgid=home-shelter-point-lifestyle-cg",
        position: { top: 0.9, left: 0.73 },
      },
      {
        item: "https://www.ralphlaurenhome.com/products/Furniture/item.aspx?haid=6&collId=&shaid=&sort=&itemId=38136&phaid=",
        position: { top: 0.9, left: 0.32 },
      },
      {
        item: "https://www.ralphlauren.com/home-furniture-tables/shelter-point-oak-cocktail-table/100001385.html?ab=en_us_PLP_shelter_point_lifestyle_Slot_5_S1_L1_SHOP",
        position: { top: 0.75, left: 0.6 },
      },
      {
        item: "https://www.ralphlauren.com/home-shelter-point-lifestyle-cg/modern-mini-hurricane/520026.html?dwvar520026_colorname=Silver&cgid=home-shelter-point-lifestyle-cg&webcat=search#ab=en_US_HomeLP_Slot_1_S1_L1_SHOP&start=1&cgid=home-shelter-point-lifestyle-cg",
        position: { top: 0.6, left: 0.62 },
      },
      {
        item: "https://www.ralphlauren.com/home-lighting-table-lamps/rl-67-boom-arm-floor-lamp/0042559294.html?pdpR=y",
        position: { top: 0.35, left: 0.68 },
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 21,
    templateType: 'video',
    videoPath: "/paris_final",
    imagePath: "/free-paris_final",
    name: "Paris café",
    maxParticipants: 4,
    shortDescription: "Sit and relax at a typical Parisian café",
    description: "A fun and relaxing experience across from the Eiffel tower",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Consulting",
      "Legal",
      "Team meeting",
      "Sounds",
      "Calming",
      "Restorative",
      "Energizing",
    ],
    usersPosition: [
      {
        bottom: 0.42,
        left: 0.4,
      },
      {
        bottom: 0.44,
        left: 0.55,
      },
      {
        bottom: 0.45,
        left: 0.65,
      },
      {
        bottom: 0.38,
        left: 0.13,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 22,
    templateType: 'video',
    videoPath: "/together_clouds",
    imagePath: "/together_clouds",
    name: "Cloud 9 (Together Mode)",
    maxParticipants: 6,
    shortDescription: "Enjoy our Together mode while floating in the clouds",
    description: "Floating in the clouds Together",
    type: "free",
    priceInCents: 1000,
    isAudioAvailable: true,
    businessCategories: ["Team meeting", "Calming", "Private", "ASMR"],
    usersPosition: [
      {
        bottom: 0.5,
        left: 0.35,
      },
      {
        bottom: 0.75,
        left: 0.425,
      },
      {
        bottom: 0.75,
        left: 0.575,
      },
      {
        bottom: 0.5,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.575,
      },
      {
        bottom: 0.25,
        left: 0.425,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 23,
    templateType: 'video',
    videoPath: "/together_clouds",
    imagePath: "/free-together_clouds",
    name: "Cloud 9 (Together Mode)",
    maxParticipants: 4,
    shortDescription: "Enjoy our Together mode while floating in the clouds",
    description: "Floating in the clouds Together",
    type: "free",
    isAudioAvailable: true,
    businessCategories: ["Team meeting", "Calming", "Private", "ASMR"],
    usersPosition: [
      {
        bottom: 0.65,
        left: 0.35,
      },
      {
        bottom: 0.65,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.35,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 24,
    templateType: 'video',
    videoPath: "/loop_campfire",
    imagePath: "/free-loop_campfire",
    name: "The Firepit (Together Mode)",
    maxParticipants: 4,
    shortDescription: "Enjoy our Together mode around a firepit",
    description: "Huddle round the fire",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Therapy",
      "Counselling",
      "Team meeting",
      "Focused",
      "Restorative",
      "Private",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.65,
        left: 0.35,
      },
      {
        bottom: 0.65,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.35,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 25,
    templateType: 'video',
    videoPath: "/loop_campfire",
    imagePath: "/loop_campfire",
    name: "The Firepit (Together Mode)",
    shortDescription: "Enjoy our Together mode around a firepit",
    description: "Huddle round the fire",
    maxParticipants: 6,
    type: "paid",
    priceInCents: 1000,
    isAudioAvailable: true,
    businessCategories: [
      "Therapy",
      "Counselling",
      "Team meeting",
      "Focused",
      "Restorative",
      "Private",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.5,
        left: 0.35,
      },
      {
        bottom: 0.75,
        left: 0.425,
      },
      {
        bottom: 0.75,
        left: 0.575,
      },
      {
        bottom: 0.5,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.575,
      },
      {
        bottom: 0.25,
        left: 0.425,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 26,
    templateType: 'video',
    videoPath: "/together_beach",
    imagePath: "/together_beach",
    name: "Vista Rica (Together Mode)",
    maxParticipants: 6,
    shortDescription:
      "Enjoy our Together mode overlooking a beautiful ocean vista",
    description: "Listen to the waves in the ocean vista",
    type: "paid",
    priceInCents: 1000,
    isAudioAvailable: true,
    businessCategories: [
      "Team meeting",
      "Consulting",
      "Coaching",
      "Focused",
      "Restorative",
      "Calming",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.5,
        left: 0.35,
      },
      {
        bottom: 0.75,
        left: 0.425,
      },
      {
        bottom: 0.75,
        left: 0.575,
      },
      {
        bottom: 0.5,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.575,
      },
      {
        bottom: 0.25,
        left: 0.425,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 28,
    templateType: 'video',
    videoPath: "/zen2-loop",
    imagePath: "/free-zen2-loop",
    name: "Zen Pond",
    maxParticipants: 4,
    shortDescription: "Zen out at the edge of a still pond",
    description: "Zen out at the edge of a still pond",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Counselling",
      "Meditation",
      "Team meeting",
      "Calming",
      "Soothing",
      "ASMR",
    ],
    usersPosition: [
      {
        bottom: 0.34,
        left: 0.385,
      },
      {
        bottom: 0.34,
        left: 0.595,
      },
      {
        bottom: 0.36,
        left: 0.795,
      },
      {
        bottom: 0.36,
        left: 0.2,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 29,
    templateType: 'video',
    videoPath: "/heart",
    imagePath: "/heart4",
    name: "Breathing Heart Exercise (Together Mode)",
    maxParticipants: 4,
    shortDescription: "Box Breathing method for anxiety and calm",
    description: "Box Breathing method for anxiety and calm",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Meditation",
      "Team meeting",
      "Calming",
      "Focused",
      "Soothing",
    ],
    usersPosition: [
      {
        bottom: 0.65,
        left: 0.35,
      },
      {
        bottom: 0.65,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.35,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 30,
    templateType: 'video',
    videoPath: "/heart",
    imagePath: "/heart6",
    name: "Breathing Heart Exercise (Together Mode)",
    shortDescription: "Box Breathing method for anxiety and calm",
    description: "Box Breathing method for anxiety and calm",
    maxParticipants: 6,
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Meditation",
      "Team meeting",
      "Calming",
      "Focused",
      "Soothing",
    ],
    usersPosition: [
      {
        bottom: 0.5,
        left: 0.35,
      },
      {
        bottom: 0.75,
        left: 0.425,
      },
      {
        bottom: 0.75,
        left: 0.575,
      },
      {
        bottom: 0.5,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.575,
      },
      {
        bottom: 0.25,
        left: 0.425,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 31,
    templateType: 'video',
    videoPath: "/abstract",
    imagePath: "/free-abstract",
    name: "Abstract Solar (Together Mode)",
    maxParticipants: 4,
    shortDescription: "A soothing background for meetings",
    description: "A soothing background for meetings",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Team meeting",
      "Consulting",
      "Coaching",
      "Focused",
      "Restorative",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.65,
        left: 0.35,
      },
      {
        bottom: 0.65,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.35,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 32,
    templateType: 'video',
    videoPath: "/abstract",
    imagePath: "/abstract",
    name: "Abstract Solar (Together Mode)",
    shortDescription: "A soothing background for meetings",
    description: "A soothing background for meetings",
    maxParticipants: 6,
    type: "paid",
    priceInCents: 1000,
    isAudioAvailable: true,
    businessCategories: [
      "Team meeting",
      "Consulting",
      "Coaching",
      "Focused",
      "Restorative",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.5,
        left: 0.35,
      },
      {
        bottom: 0.75,
        left: 0.425,
      },
      {
        bottom: 0.75,
        left: 0.575,
      },
      {
        bottom: 0.5,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.575,
      },
      {
        bottom: 0.25,
        left: 0.425,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 33,
    templateType: 'image',
    imagesUrl: "/free-calm6",
    imagePath: "/free-calm6",
    name: "Simply Nice (Together Mode)",
    maxParticipants: 4,
    description: "A static, professional & calming ambient",
    shortDescription: "A static, professional & calming ambient",
    type: "free",
    isAudioAvailable: false,
    businessCategories: [
      "Team meeting",
      "Consulting",
      "Coaching",
      "Focused",
      "Restorative",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.65,
        left: 0.35,
      },
      {
        bottom: 0.65,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.35,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 34,
    templateType: 'image',
    imagesUrl: "/calm6",
    imagePath: "/calm6",
    name: "Simply Nice (Together Mode)",
    maxParticipants: 6,
    description: "A static, professional & calming ambient",
    shortDescription: "A static, professional & calming ambient",
    type: "paid",
    priceInCents: 1000,
    isAudioAvailable: false,
    businessCategories: [
      "Team meeting",
      "Consulting",
      "Coaching",
      "Focused",
      "Restorative",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.5,
        left: 0.35,
      },
      {
        bottom: 0.75,
        left: 0.425,
      },
      {
        bottom: 0.75,
        left: 0.575,
      },
      {
        bottom: 0.5,
        left: 0.65,
      },
      {
        bottom: 0.25,
        left: 0.575,
      },
      {
        bottom: 0.25,
        left: 0.425,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 36,
    templateType: 'video',
    videoPath: "/perk_central",
    imagePath: "/perk_central",
    name: "Perk Central",
    maxParticipants: 6,
    description: "This place calls for friends or making friends",
    shortDescription: "This place calls for friends or making friends",
    type: "paid",
    priceInCents: 2000,
    isAudioAvailable: true,
    businessCategories: [
      "Consulting",
      "Coaching",
      "Team meeting",
      "Energizing",
      "Fun",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.58,
        left: 0.43,
      },
      {
        bottom: 0.58,
        left: 0.51,
      },
      {
        bottom: 0.58,
        left: 0.63,
      },
      {
        bottom: 0.46,
        left: 0.92,
      },
      {
        bottom: 0.58,
        left: 0.22,
      },
      {
        bottom: 0.60,
        left: 0.06,
      },
    ],
    draft: false,
    isPublic: true,
  },
  {
    templateId: 37,
    templateType: 'video',
    videoPath: "/perk_central",
    imagePath: "/free-perk_central",
    name: "Perk Central",
    maxParticipants: 4,
    description: "This place calls for friends or making friends",
    shortDescription: "This place calls for friends or making friends",
    type: "free",
    isAudioAvailable: true,
    businessCategories: [
      "Consulting",
      "Coaching",
      "Team meeting",
      "Energizing",
      "Fun",
      "Calming",
    ],
    usersPosition: [
      {
        bottom: 0.58,
        left: 0.43,
      },
      {
        bottom: 0.58,
        left: 0.59,
      },
      {
        bottom: 0.74,
        left: 0.21,
      },
      {
        bottom: 0.46,
        left: 0.92,
      },
    ],
    draft: false,
    isPublic: true,
  },
];
