import { ConfigKeysType } from "./config.interface";

export const ConfigKeys: readonly ConfigKeysType[] = [
  "rabbitMqCoreQueue",
  "rabbitMqSocketQueue",
  "rabbitMqAuthQueue",
  "rabbitMqNotificationsQueue",
  "rabbitMqMediaServerQueue",
  "rabbitMqScalingQueue",
  "rabbitMqPaymentQueue",
  "rabbitMqUser",
  "rabbitMqPass",
  "rabbitMqHost",
  "rabbitMqCoreHost",
  "rabbitMqCorePort",

  "vultrUploadBucket",
  "vultrStorageHostname",
  "vultrAccessKey",
  "vultrSecretAccessKey",
  "vultrSnapshotId",
  "vultrApiKey",

  "stripeApiKey",
  "stripeWebhookSecret",
  "stripeExpressWebhookSecret",

  "livekitApiKey",
  "livekitApiSecret",
  "livekitHost",

  "environment",
  "isLocal",
  "port",
  "nodeEnv",
  "emailService",
  "defaultServerIp",
  "defaultDomain",
  "frontendUrl",
  "gatewayPort",
  "jwtSecret",
  "mongoUri",
  "smtpUser",
  "smtpPass",
  "smtpUserName",
  "mandrillApiKey",
  "supportScaling",
  "numberOfActiveServers",
  "supportEmail",
];

export const DefaultConfigValues: Record<
  ConfigKeysType,
  string | number | boolean
> = {
  rabbitMqCoreQueue: "rabbitMqCoreQueue",
  rabbitMqSocketQueue: "rabbitMqSocketQueue",
  rabbitMqAuthQueue: "rabbitMqAuthQueue",
  rabbitMqNotificationsQueue: "rabbitMqNotificationsQueue",
  rabbitMqMediaServerQueue: "rabbitMqMediaServerQueue",
  rabbitMqScalingQueue: "rabbitMqScalingQueue",
  rabbitMqPaymentQueue: "rabbitMqPaymentQueue",
  rabbitMqUser: "rabbituser",
  rabbitMqPass: "rabbitpass",
  rabbitMqHost: "rabbitmq",
  rabbitMqCoreHost: "rabbitmq",
  rabbitMqCorePort: "5672",
  mongoUri: "mongodb://mongo:27017/theliveoffice",
  jwtSecret: "jwtSecret",
  frontendUrl: "http://localhost:8000",
  gatewayPort: "3000",
  smtpUser: "vladislav.e@fora-soft.com",
  smtpPass: "xoiwmfwquupyhcoj",
  smtpUserName: "The LiveOffice",
  defaultServerIp: "localhost",
  defaultDomain: "localhost",
  vultrUploadBucket: "liveoffice",
  vultrStorageHostname: "ewr1.vultrobjects.com",
  vultrAccessKey: "XSGnjAdSXoRYhTAntNNJYhHCY7MeJseUujCDvcHK",
  vultrSecretAccessKey: "04F4BOA4E0QRBSF0BW37",
  vultrSnapshotId: "",
  vultrApiKey: "",
  livekitApiKey: "apikey",
  livekitApiSecret: "apisecret",
  livekitHost: "http://livekit-service:7880",
  stripeApiKey: "",
  stripeWebhookSecret: "",
  stripeExpressWebhookSecret: "",
  mandrillApiKey: "",
  isLocal: false,
  nodeEnv: "develop",
  port: 4000,
  emailService: "gmail",
  environment: "local",
  supportScaling: false,
  numberOfActiveServers: 0,
  supportEmail: "foratestqa+liveofficesupport@gmail.com",
};
