version: "3.8"
name: proxy

services:
  traefik:
    build: ./traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:9090:9090"
      # close or move dashboard port to the save place
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`tlo-traefik.anhtuan57.click`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=auth"
      # echo $(htpasswd -nb tlo 02HBdnBT2ZPu) | sed -e s/\\$/\\$\\$/g
      - "traefik.http.middlewares.auth.basicauth.users=tlo:$$apr1$$PdvDQIVp$$UAXSS/z5O5t.VQm7acCfh1"
    networks:
      - traefikpublic

  instance-proxy:
    container_name: instance_proxy
    build:
      context: ../../services/instance-proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7000:7000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefikpublic"
      - "traefik.http.routers.proxy.rule=HostRegexp(`{subdomain:.+}.scaling.anhtuan57.click`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls.certresolver=wildcard-resolver"
      - "traefik.http.routers.proxy.tls.domains[0].main=scaling.anhtuan57.click"
      - "traefik.http.routers.proxy.tls.domains[0].sans=*.scaling.anhtuan57.click"
      - "traefik.http.services.proxy.loadbalancer.server.port=7000"
      - "io.portainer.accesscontrol.public"
    networks:
      - traefikpublic

  whoami:
    image: "traefik/whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefikpublic"
      - "traefik.http.routers.whoami.rule=(Host(`aws.nongdan.dev`) || Host(`aws-socket.nongdan.dev`) || Host(`tlo-livekit.anhtuan57.click`) || Host(`tlo-traefik.anhtuan57.click`)) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=simple-resolver"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefikpublic

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
#    networks:
#      - traefikpublic
networks:
  traefikpublic:
    name: traefikpublic
volumes:
  data: