version: "3.8"

services:
  traefik:
    build: ./traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/letsencrypt:/letsencrypt
    networks:
      - traefik

  whoami:
    image: "traefik/whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.whoami.rule=Host(`theliveoffice.com`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls.certresolver=simple-resolver"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik


networks:
  traefik:
    external:
      name: traefik
