.production:
  extends:
    - .docker-base
  tags: [LiveOfficeProd-deploy]
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(production)$/'
      when: manual
      allow_failure: true

Update Production Traefik:
  extends:
    .production
  stage: update_production_traefik
  script:
    - cd deploy/production
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice -f docker-compose.traefik.yml up -d --build
  interruptible: true

Update Production:
  stage: update_production
  extends:
    - .production
  script:
    - cd deploy/production
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice_${CI_COMMIT_REF_NAME} -f docker-compose.${CI_COMMIT_REF_NAME}.yml up -d --build
  interruptible: true