.production:
  extends:
    - .docker-base
  tags: [LiveOfficeProd-deploy]
  only:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^(production)$/

Update Production Traefik:
  stage: update_production_traefik
  extends:
    .production
  script:
    - cd deploy/production
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice -f docker-compose.traefik.yml up -d --build --force-recreate --remove-orphans
  interruptible: true

Update Production:
  stage: update_production
  extends:
    - .production
  script:
    - cd deploy/production
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice_${CI_COMMIT_REF_NAME} -f docker-compose.${CI_COMMIT_REF_NAME}.yml up -d --build --force-recreate --remove-orphans
  interruptible: true