.staging:
  extends:
    - .docker-base
  tags: [liveoffice-deploy]
  only:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^(develop|testing)$/

Update Traefik:
  stage: update_traefik
  extends:
    - .staging
  script:
    - cd deploy/develop
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice -f docker-compose.traefik.yml up -d --build
  interruptible: true

Update Staging:
  stage: update
  extends:
    - .staging
  script:
    - cd deploy/develop
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice_${CI_COMMIT_REF_NAME} -f docker-compose.yml -f docker-compose.${CI_COMMIT_REF_NAME}.yml up -d --build
  interruptible: true

Update Jira Issues:
  stage: update_jira_issues
  image: docker:19.03.5-dind
  before_script:
    - apk update
    - apk add --no-cache curl
  script:
    - echo "${JIRA_ISSUE_UPDATER_TOKEN}"
    - |
      curl -X POST \
        https://jira-issue-updater.staging.forasoft.com/update \
        -H 'Content-Type: application/json' \
        -H 'cache-control: no-cache' \
        -d '{
        "project": "LOF",
        "from": "resolved",
        "to": "Ready for testing",
        "comment": "'"Build from ${CI_COMMIT_SHA}"'",
        "token": "'"${JIRA_ISSUE_UPDATER_TOKEN}"'"
        }'
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^testing$/'
      when: manual
