.staging:
  extends:
    - .docker-base
  tags: [liveoffice-deploy]
  only:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^(develop|testing)$/
  except:
    variables:
      - $CLIENT_PUSH_ACTIVE == "true"

Update Traefik:
  stage: update_traefik
  extends:
    - .staging
  script:
    - cd deploy/develop
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice -f docker-compose.traefik.yml up -d --build --force-recreate --remove-orphans
  interruptible: true

Update Staging:
  stage: update
  extends:
    - .staging
  script:
    - cd deploy/develop
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice_${CI_COMMIT_REF_NAME} -f docker-compose.yml -f docker-compose.${CI_COMMIT_REF_NAME}.yml up -d --build
  interruptible: true
  except: [testing]


Update_Test:
  stage: update
  extends:
    - .staging
  script:
    - cd deploy/develop
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p liveoffice_${CI_COMMIT_REF_NAME} -f docker-compose.yml -f docker-compose.${CI_COMMIT_REF_NAME}.yml up -d --build
  interruptible: true
  only: [testing]
  when: manual
  allow_failure: false

include:
  - 'pipelines/jira.yml'