FROM node:18.9.1-alpine

RUN apk add --no-cache curl && curl -sL https://unpkg.com/@pnpm/self-installer | node

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache g++ make

WORKDIR /app

RUN mkdir -p services/notification-service

COPY ./pnpm-workspace.yaml ./
COPY ./.npmrc ./
COPY ./shared ./shared

RUN pnpm add nx -D -w

COPY ./services/notification-service/package.json ./services/notification-service

COPY ./services/notification-service ./services/notification-service

RUN pnpm install

RUN npx nx run-many --target=build --projects=shared-utils,shared-const,shared-types

CMD /wait && pnpm --filter notification-service dev
