log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: liveoffice_traefikpublic
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    watch: true
    directory: /etc/traefik/dynamic

accessLog: {}

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: :443