export const BUSINESS_CATEGORIES = [
    { key: 'accounting', value: 'Accounting', color: '#2915a0' },
    { key: 'bookkeeping', value: 'Bookkeeping', color: '#2f3edc' },
    { key: 'businessAnalysis', value: 'Business Analysis', color: '#914b50' },
    { key: 'financialAnalysis', value: 'Financial Analysis', color: '#1f2418' },
    { key: 'financialManagement', value: 'Financial Management', color: '#a698c0' },
    { key: 'hr', value: 'HR', color: '#43e220' },
    { key: 'managementConsulting', value: 'Consulting', color: '#603f50' },
    { key: 'instructionalDesign', value: 'Design', color: '#deb550' },
    { key: 'recruiting', value: 'Recruiting', color: '#6912a0' },
    { key: 'itNetworking', value: 'IT & Networking', color: '#dc7e10' },
    { key: 'tax', value: 'Tax Preparation', color: '#7a785b' },
    { key: 'legal', value: 'Legal', color: '#b4c9e0' },
    { key: 'sales', value: 'Sales & Marketing', color: '#ea392f' },
    { key: 'dataEntry', value: 'Data Entry', color: '#9ecd50' },
    { key: 'training', value: 'Training', color: '#da2690' },
    { key: 'translation', value: 'Translation', color: '#5734fd' },
    { key: 'softwareDevelopment', value: 'Software Development', color: '#517f60' },
    { key: 'onlineResearch', value: 'Research', color: '#5ba555' },
    { key: 'orderProcessing', value: 'Processing', color: '#382ba8' },
    { key: 'transcription', value: 'Transcription', color: '#1ee510' },
    { key: 'projectManagement', value: 'Project Management', color: '#3219ad' },
    { key: 'virtualAssistance', value: 'Virtual Assistance', color: '#666321' },
    { key: 'customerService', value: 'Customer Service', color: '#33206a' },
    { key: 'technicalSupport', value: 'Technical Support', color: '#b77b97' },
    { key: 'a&bTesting', value: 'A/B Testing', color: '#81f650' },
    { key: 'Bandits', value: 'Bandits', color: '#d55f80' },
    { key: 'dataAnalytics', value: 'Data Analytics', color: '#5c946f' },
    { key: 'dataEngineering', value: 'Data Engineering', color: '#3ed451' },
    { key: 'dataExtraction', value: 'Data Extraction', color: '#6a40de' },
    { key: 'dataMining', value: 'Data Mining', color: '#d57d99' },
    { key: 'dataProcessing', value: 'Data Processing', color: '#dc3128' },
    { key: 'dataVisualization', value: 'Data Visualization', color: '#58e39b' },
    { key: 'deepLearning', value: 'Deep Learning', color: '#53b956' },
    { key: 'testing', value: 'Testing', color: '#83e114' },
    { key: 'ml', value: 'Machine Learning', color: '#b0736e' },
    { key: 'artDirection', value: 'Art Direction', color: '#5d28c8' },
    { key: 'actor', value: 'Actor', color: '#57cb7c' },
    { key: 'audioEditing', value: 'Audio Editing', color: '#1f988e' },
    { key: 'audioProduction', value: 'Audio Production', color: '#565de6' },
    { key: 'postProduction', value: 'Post-Production', color: '#bf1770' },
    { key: 'brandIdentityDesign', value: 'Brand Identity Design', color: '#ce9e8b' },
    { key: 'cartoonist', value: 'Cartoonist', color: '#dee9c2' },
    { key: 'illustration', value: 'Illustration', color: '#fb2e3f' },
    { key: 'videographer', value: 'Videographer', color: '#3dc4d9' },
];
