version: "3.7"
services:
  turn:
    image: coturn/coturn:latest
    network_mode: "host"
    restart: always
    volumes:
      - ./turn/turnserver.conf:/etc/coturn/turnserver.conf
      - ./ssl:/ssl
