FROM node:18.7.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app

COPY ./shared ./shared

RUN mkdir ./scaling-service

COPY ./scaling-service/package*.json ./scaling-service/

RUN npm ci --silent --legacy-peer-deps --force --prefix=/app/scaling-service

COPY ./scaling-service ./scaling-service/

RUN npm run build --prefix=/app/scaling-service

EXPOSE 6000

CMD /wait && npm run start:dev --prefix=/app/scaling-service

