FROM node:16.16.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./socket-service/

COPY ./socket-service/package*.json ./socket-service/

RUN cd ./socket-service && npm i --legacy-peer-deps

COPY ./socket-service ./socket-service/

RUN cd ./socket-service && npm run build

EXPOSE 8080

CMD /wait && npm run --prefix=/app/socket-service start:dev
