tlo:
  children:
    production:
      hosts:
        liveofficeProd:
          ansible_host: 18.118.59.1


all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /root/.ssh/nongdan.dev
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    scp_if_ssh: true
    ansible_connection: ssh
    command_warnings: False
