# ansible-playbook main.yml -i inventory.yml -l liveofficeStaging-aws -t "all"
- hosts: production
  become: true
  roles:
    - role: common

- hosts: Staging
  become: true
  roles:
    - role: common

- hosts: turn-server
  become: true
  roles:
    - role: common
  tasks:
    - name: copy turn-server
      ansible.builtin.copy:
        src: files/turn-server
        dest: /srv/
        follow: yes
      tags:
        - turn-server
        - all
    - name: docker-compose up
      shell:
        cmd: |
          cd /srv/turn-server
          docker-compose up -d
        warn: False
      tags:
        - turn-server
        - all