FROM node:16.14.0-alpine

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./gateway-service

COPY ./gateway-service/package*.json ./gateway-service/

RUN cd ./gateway-service && npm i --legacy-peer-deps

COPY ./gateway-service ./gateway-service/

EXPOSE 3000

CMD ["npm", "run", "--prefix", "/app/gateway-service", "start:dev"]
