npm i --prefix=services/auth-service
npm i --prefix=services/config-service
npm i --prefix=services/core-service
npm i --prefix=services/frontend-service --force --legacy-peer-deps
npm i --prefix=services/gateway-service
npm i --prefix=services/notifications-service
npm i --prefix=services/payment-service --force
npm i --prefix=services/socket-service
npm i --prefix=services/meeting-socket-service
npm i --prefix=services/scaling-service
npm i --prefix=services/media-server-service
