FROM node:16.16.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./meeting-socket-service/

COPY ./meeting-socket-service/package*.json ./meeting-socket-service/

RUN cd ./meeting-socket-service && npm i --legacy-peer-deps

COPY ./meeting-socket-service ./meeting-socket-service/

RUN cd ./meeting-socket-service && npm run build

EXPOSE 8180

CMD /wait && npm run --prefix=/app/meeting-socket-service start:dev
