FROM node:18.7.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./meeting-socket-service/

COPY ./meeting-socket-service/package*.json ./meeting-socket-service/

RUN npm ci --legacy-peer-deps --silent --prefix=/app/meeting-socket-service

COPY ./meeting-socket-service ./meeting-socket-service/

RUN npm run build --prefix=/app/meeting-socket-service

EXPOSE 8180

CMD /wait && npm run start:dev --prefix=/app/meeting-socket-service
