FROM node:16.14.0-alpine

WORKDIR /app/

COPY ./shared ./shared

RUN mkdir ./notifications-service

COPY ./notifications-service/package*.json ./notifications-service/

RUN cd ./notifications-service && npm ci --silent --legacy-peer-deps

COPY ./notifications-service ./notifications-service/

CMD ["npm", "run", "--prefix", "/app/notifications-service", "start:dev"]
