FROM node:16.16.0-alpine

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache g++ make

RUN mkdir /app
WORKDIR /app

COPY ./shared ./shared

RUN mkdir ./notifications-service

COPY ./notifications-service/package*.json ./notifications-service/

RUN cd ./notifications-service && npm ci --silent --legacy-peer-deps

COPY ./notifications-service ./notifications-service/

CMD ["npm", "run", "--prefix", "/app/notifications-service", "dev"]
