#    - name: Install net packages
#      shell: |
#        apt-get update
#        apt-get -y net-tools nload
#      tags:
#        - install
# ==================================================================
- name: Check docker exists
  stat:
    path: /usr/bin/docker
  register: docker_exist
  tags:
    - docker
    - all

- name: Install docker packages
  shell:
    cmd: |
      sudo apt-get update
      sudo apt-get -y install ca-certificates curl gnupg
      sudo install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo chmod a+r /etc/apt/keyrings/docker.gpg
      echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      
      sudo apt-get update
      
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    warn: False
  when: not docker_exist.stat.exists
  tags:
    - docker
    - all

# ==================================================================

- name: Check /etc/rc.local exists
  stat:
    path: /etc/rc.local
  register: rc_local_exist
  tags:
    - rc.local
    - all

- name: enable /etc/rc.local
  ansible.builtin.shell: |
    echo '#!/bin/bash' > /etc/rc.local
    chmod +x /etc/rc.local
    systemctl start rc-local
  when: not rc_local_exist.stat.exists
  tags:
    - rc.local
    - all
# ==================================================================

- name: Check docker-compose exists
  stat:
    path: /usr/bin/docker-compose
  register: docker_compose_exist
  tags:
    - docker-compose
    - all

- name: Install docker compose
  ansible.builtin.shell: |
    curl -SL https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  when: not docker_compose_exist.stat.exists
  tags:
    - docker-compose
    - all

# ==================================================================
- name: Check swap exists
  stat:
    path: /swap
  register: swap_exist
  tags:
    - swap
    - all

- name: Setup swap
  ansible.builtin.shell: |
    dd if=/dev/zero of=/swap count=4096 bs=1MiB
    chmod 600 /swap
    mkswap /swap
    swapon /swap
    echo "swapon /swap" >> /etc/rc.local
    cat /etc/rc.local
  when: not swap_exist.stat.exists
  tags:
    - swap
    - all
# ==================================================================

- name: Ensure clean up old images if disk almost full job exists.
  ansible.builtin.cron:
    name: "clean up old images if disk almost full"
    minute: "0"
    job: sh -c "if [ $(df / --output='pcent' | grep -o "[0-9]*") -gt 90 ]; then docker system prune -f; fi"
  tags:
    - cronjob
    - all