FROM node:18.9.1-alpine

RUN apk add --no-cache curl && curl -sL https://unpkg.com/@pnpm/self-installer | node

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app

RUN mkdir -p services/auth-service

COPY ./pnpm-workspace.yaml ./
COPY ./.npmrc ./
COPY ./shared ./shared

RUN pnpm add nx -D -w

COPY ./services/auth-service/package.json ./services/auth-service

RUN pnpm install

COPY ./services/auth-service ./services/auth-service

RUN npx nx run-many --target=build --projects=shared-const,shared,auth-service

CMD /wait && pnpm --filter auth-service start:dev
