FROM node:18.9.1-alpine

RUN apk add --no-cache curl && curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | PNPM_VERSION=8.15.5 node

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

RUN apk update
RUN apk add ffmpeg

WORKDIR /app/

RUN mkdir -p services/core-service

COPY ./pnpm-workspace.yaml ./
COPY ./.npmrc ./
COPY ./shared ./shared

RUN pnpm add nx -D -w

COPY ./services/core-service/package.json ./services/core-service

COPY ./services/core-service ./services/core-service

RUN pnpm install

RUN npx nx run-many --target=build --projects=shared-types,shared-const,shared-utils

CMD /wait && pnpm --filter core-service start:dev
