# This is a basic workflow to help you get started with Actions

name: deploy production aws

# Controls when the action will run. 
on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - 'production'
  push:
    branches:
      - 'production'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: liveofficeProd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production

      - name: Update Traefik
        run: |
          cd deploy/production
          docker-compose -f docker-compose.proxy.yml up -d --build --force-recreate --remove-orphans

      - name: Deploy new source
        run: |
          cd deploy/production
          rsync -av env ../../services/config-service/.env
          docker-compose -f docker-compose.services.yml up -d --build --remove-orphans
