version: "3.7"

networks:
  traefikpublic:

services:
  traefik:
    build: ../../services/traefik
    restart: always
    labels:
      - "io.portainer.accesscontrol.public"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/archive/livekit.liveoffice.forasoft.com-0001:/etc/certs/
      - /data/traefik/config/certs-traefik.yaml:/etc/traefik/dynamic/certs-traefik.yaml
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:9090:9090"
    networks:
      - traefikpublic

  instance-proxy:
    container_name: instance_proxy
    build:
      context: ../../services/instance-proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7000:7000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy_dev.rule=HostRegexp(`{subdomain:.+}.scaling.liveoffice.forasoft.com`)"
      - "traefik.http.routers.proxy_dev.entrypoints=https"
      - "traefik.http.routers.proxy_dev.tls=true"
      - "traefik.http.services.proxy_dev.loadbalancer.server.port=7000"
      - "io.portainer.accesscontrol.public"
    networks:
      - traefikpublic

  whoami:
    image: "traefik/whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=liveoffice_traefikpublic"
      - "traefik.http.routers.whoami.rule=Host(`whoami.liveoffice.forasoft.com`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefikpublic
