version: "3.7"

networks:
  default:
    external:
      name: liveoffice_network
  liveoffice_local:
      name: liveoffice_local

services:
  mongo:
    container_name: liveoffice_mongo
    ports:
      - '127.0.0.1:56100:27017'
    volumes:
      - ~/data/liveoffice/mongo:/data/db
    networks:
      - liveoffice_local

  rabbit:
    container_name: liveoffice_rabbit
    ports:
      - '5672:5672'
    networks:
      - liveoffice_local

  frontend-service:
    container_name: liveoffice_frontend
    build:
      context: ../../frontend-service
      dockerfile: Dockerfile.dev
      args:
        - STORAGE_HOSTNAME=ewr1.vultrobjects.com
    depends_on:
      - gateway-service
    ports:
      - '8000:8000'
    environment:
      - GATEWAY_PORT=3000
      - GATEWAY_HOST=gateway-service
      - FRONTEND_URL=http://localhost:8000
      - GATE_WAY_URL=http://gateway-service:3000
      - TURN_URL=78.46.107.230
      - TURN_PASSWORD=kurentoturnpassword
      - TURN_USERNAME=kurentoturn
      - TURN_PORT=3486
      - STORAGE_HOSTNAME=ewr1.vultrobjects.com
    volumes:
      - type: bind
        source: ../../frontend-service/pages
        target: /app/pages
      - type: bind
        source: ../../frontend-service/src
        target: /app/src
      - type: bind
        source: ../../frontend-service/public
        target: /app/public
    networks:
      - liveoffice_local

  gateway-service:
    container_name: liveoffice_gateway
    build:
      context: ../../
      dockerfile: ./gateway-service/Dockerfile.dev
    depends_on:
      - core-service
      - auth-service
      - notifications-service
    ports:
      - '3000:3000'
    volumes:
      - ../../gateway-service:/app/gateway-service
      - ../../shared:/app/shared
      - /app/gateway-service/dist
    networks:
      - liveoffice_local

  core-service:
    container_name: liveoffice_core
    build:
      context: ../../
      dockerfile: ./core-service/Dockerfile.dev
    depends_on:
      - config-service
    volumes:
      - ../../core-service:/app/core-service
      - ../../shared:/app/shared
      - /app/core-service/dist
    networks:
      - liveoffice_local

  auth-service:
    container_name: liveoffice_auth
    build:
      context: ../../
      dockerfile: ./auth-service/Dockerfile.dev
    depends_on:
      - config-service
    volumes:
      - ../../auth-service:/app/auth-service
      - ../../shared:/app/shared
      - /app/auth-service/dist
    networks:
      - liveoffice_local

  notifications-service:
    container_name: liveoffice_notifications
    build:
      context: ../../
      dockerfile: ./notifications-service/Dockerfile.dev
    depends_on:
      - config-service
    volumes:
      - ../../notifications-service:/app/notifications-service
      - ../../shared:/app/shared
      - /app/notifications-service/dist
    networks:
      - liveoffice_local

  socket-service:
    container_name: liveoffice_socket
    build:
      context: ../../
      dockerfile: ./socket-service/Dockerfile.dev
    depends_on:
      - rabbit
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ../../socket-service:/app/socket-service
      - ../../shared:/app/shared
      - /app/socket-service/dist
    networks:
      - liveoffice_local

  config-service:
    container_name: liveoffice_config
    build:
      context: ../../
      dockerfile: ./config-service/Dockerfile.dev
    environment:
      - RABBIT_MQ_CORE_QUEUE=rabbitMqCoreQueue
      - RABBIT_MQ_AUTH_QUEUE=rabbitMqAuthQueue
      - RABBIT_MQ_NOTIFICATIONS_QUEUE=rabbitMqNotificationsQueue
      - RABBIT_MQ_USER=rabbituser
      - RABBIT_MQ_PASS=rabbitpass
      - RABBIT_MQ_HOST=rabbitmq
      - FRONTEND_URL=http://localhost:8000
      - GATEWAY_PORT=3000
      - JWT_SECRET=jwtSecret
      - MONGO_URI=mongodb://mongo:27017/theliveoffice
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=foratestqa@gmail.com
      - SMTP_PASS=asdfghjkL2
      - DEFAULT_SERVER_IP=localhost
      - APP_ID=9d88cb47f5e648c1b2b3c6ee8563e655
      - APP_CERTIFICATE=5eeb44cc55e94718ab3cdde84f278174
      - UPLOAD_BUCKET=liveoffice
      - STORAGE_HOSTNAME=ewr1.vultrobjects.com
      - SECRET_ACCESS_KEY=XSGnjAdSXoRYhTAntNNJYhHCY7MeJseUujCDvcHK
      - ACCESS_KEY=04F4BOA4E0QRBSF0BW37
    depends_on:
      - mongo
      - rabbit
    volumes:
      - ../../config-service:/app/config-service
      - ../../shared:/app/shared
      - /app/config-service/dist
    networks:
      - liveoffice_local


