version: '3.7'

networks:
  traefikpublic:
    external:
      name: liveoffice_traefikpublic
  liveoffice_test:

services:
  mongo:
    ports:
      - '127.0.0.1:56200:27017'
    volumes:
      - /data/liveoffice/testing/mongo:/data/db
    networks:
      - liveoffice_test

  rabbit:
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - /data/liveoffice/testing/rabbit:/var/lib/rabbitmq
    networks:
      - liveoffice_test

  frontend-service:
    build: ../../frontend-service
    depends_on:
      - gateway-service
    restart: always
    ports:
      - '8100:8000'
    environment:
      - FRONTEND_URL=https://test-liveoffice.staging.forasoft.com
      - GATEWAY_PORT=3000
      - GATEWAY_HOST=gateway-service
      - GATE_WAY_URL=http://gateway-service:3000
      - TURN_URL
      - TURN_PASSWORD
      - TURN_USERNAME
      - TURN_PORT
      - STORAGE_HOSTNAME
      - STRIPE_PUBLIC_API_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front_test.rule=Host(`test-liveoffice.staging.forasoft.com`)"
      - "traefik.http.routers.front_test.entrypoints=http"
      - "traefik.http.services.front_test.loadbalancer.server.port=8000"
    networks:
      - traefikpublic
      - liveoffice_test

  gateway-service:
    build:
      context: ../../
      dockerfile: ./gateway-service/Dockerfile
    restart: always
    ports:
      - '3100:3000'
    depends_on:
      - mongo
      - rabbit
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway_test.rule=Host(`test-liveoffice.staging.forasoft.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.gateway_test.entrypoints=http"
      - "traefik.http.services.gateway_test.loadbalancer.server.port=3000"
    networks:
      - traefikpublic
      - liveoffice_test

  socket-service:
    build:
      context: ../../
      dockerfile: ./socket-service/Dockerfile
    restart: always
    ports:
      - '8081:8080'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socket_test.rule=Host(`test-liveoffice.staging.forasoft.com`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.socket_test.entrypoints=http"
      - "traefik.http.services.socket_test.loadbalancer.server.port=8080"
    networks:
      - traefikpublic
      - liveoffice_test

  core-service:
    build:
      context: ../../
      dockerfile: ./core-service/Dockerfile
    restart: always
    depends_on:
      - config-service
    networks:
      - liveoffice_test

  auth-service:
    build:
      context: ../../
      dockerfile: ./auth-service/Dockerfile
    restart: always
    depends_on:
      - config-service
    networks:
      - liveoffice_test

  notifications-service:
    build:
      context: ../../
      dockerfile: ./notifications-service/Dockerfile
    restart: always
    depends_on:
      - config-service
    networks:
      - liveoffice_test

  payment-service:
    build:
      context: ../../
      dockerfile: ./payment-service/Dockerfile
    restart: always
    depends_on:
      - config-service
    networks:
      - liveoffice_test

  config-service:
    build:
      context: ../../
      dockerfile: ./config-service/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - EMAIL_SERVICE
      - RABBIT_MQ_CORE_QUEUE=rabbitMqCoreQueue
      - RABBIT_MQ_AUTH_QUEUE=rabbitMqAuthQueue
      - RABBIT_MQ_PAYMENT_QUEUE=rabbitMqPaymentQueue
      - RABBIT_MQ_NOTIFICATIONS_QUEUE=rabbitMqNotificationsQueue
      - RABBIT_MQ_USER
      - RABBIT_MQ_PASS
      - RABBIT_MQ_HOST
      - GATEWAY_PORT=3000
      - FRONTEND_URL=https://test-liveoffice.staging.forasoft.com
      - JWT_SECRET
      - MONGO_URI
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - DEFAULT_SERVER_IP
      - APP_ID
      - APP_CERTIFICATE
      - UPLOAD_BUCKET
      - STORAGE_HOSTNAME
      - SECRET_ACCESS_KEY
      - ACCESS_KEY
      - STRIPE_API_KEY
      - STRIPE_WEBHOOK_SECRET
      - STRIPE_EXPRESS_WEBHOOK_SECRET
      - MANDRILL_API_KEY
    depends_on:
      - mongo
      - rabbit
    networks:
      - liveoffice_test