export enum MeetingSubscribeEvents {
    OnGetMeetingNotes = 'meeting:notes:get',
    OnGetMeetingReactions = 'meeting:reaction:get',
    OnUpdateMeeting = 'meeting:update',
    OnUserAccepted = 'meeting:userAccepted',
    OnMeetingEnterRequest = 'meeting:accessRequest:receive',
    OnFinishMeeting = 'meeting:finished',
    OnUpdateMeetingTemplate = 'template:update',
    OnSendMeetingNote = 'meeting:notes:create',
    OnRemoveMeetingNote = 'meeting:notes:delete',
    OnSendMeetingReaction = 'meeting:reaction:create',
    OnRemoveMeetingReaction = 'meeting:reaction:delete',
    OnMeetingError = 'meeting:error',
    OnPlaySound = 'meeting:sounds.play',
    OnMeetingTimeLimit = 'meeting:timeLimit',
    OnReceiveMessage = 'meeting:chat:message:receive',
    OnReceiveReaction = 'meeting:chat:reaction:receive',
    OnReceiceUnReaction = 'meeting:chat:unreaction:receive',
    OnRejoinWaitingRoom = 'meeting:rejoin',
    OnReceiveQuestion = 'meeting:question:question:receive',
    OnReceiveQuestionReaction = 'meeting:question:reaction:receive',
    OnReceiceQuestionUnReaction = 'meeting:question:unreaction:receive',
    OnReceiveRequestRecording = 'meeting:recording:request:receive',
}
