FROM node:16.16.0-alpine

WORKDIR /app

COPY ./package*.json ./

RUN npm ci --silent --legacy-peer-deps

ARG STORAGE_HOSTNAME
ENV STORAGE_HOSTNAME=$STORAGE_HOSTNAME

COPY . .

RUN npm run build

EXPOSE 8000

CMD ["npm", "run", "dev"]
